name: Create script Links in Readme

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate scripts link in readme.md
        run: node ./scripts/genelate-scripts-link.js > ./readme.md

      # https://zenn.dev/snowcait/articles/903d86d668fcb7
      - name: Check if there are any changes
        id: verify_diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Commit
        run: |
          set -x
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add readme.md
          git commit -m 'docs(script-links): update script links in readme.md'
          git push
        if: steps.diff.outcome == 'failure'
